### ISSUE TITLE
Sort list by card number?

### ISSUE THREAD

**Issue by jdanish** [Kamalisk/arkhamdb#25] opened 2016-11-29 02:45 UTC
Thanks so much for making this! Is there any chance of having a way to display a deck-list with card numbers in card number order? I like to store my cards all in order and being able to pull cards quickly based on a list would be awesome. Assuming I am not missing this feature already in there?  Thanks again for making this!

**Comment by Kamalisk** [comment] 2016-11-29 12:59
Planning to let you sort deck lists .. eventually :P

**Comment by mattsigal** [comment] 2016-11-29 13:10
Duplicate of #15

**Comment by jdanish** [comment] 2016-11-30 17:10
Thanks and sorry for the duplicate! Either way, really appreciative of all your efforts!

**Closed as completed** 2017-02-02 23:10 UTC
