### ISSUE TITLE
Bless and Curse tokens/text missing in hover view

### ISSUE THREAD

**Issue by jasonconlon** [Kamalisk/arkhamdb#373] opened 2020-11-19 23:54 UTC
In both the deckbuilding and card search screens, when you hover over a card to view its text, it does not display "[bless]"/"[curse]" text on cards with this symbol.  It does correctly display on the actual card page (when you click through to view it), though.

E.g.
In the hover view, Crisis of Faith displays incorrectly as:
**Revelation -** For each token in the chaos bag, you must either replace it with a token or take 1 horror.

In the card page, Crisis of Faith displays correctly as:
**Revelation -** For each [bless] token in the chaos bag, you must either replace it with a [curse] token or take 1 horror.

**Comment by bzly** [comment] 2020-11-30 07:11
This issue is a duplicate of #349 :)

**Comment by Kamalisk** [comment] 2020-12-24 19:10
should be fixed now.

**Closed as completed by Kamalisk** 2020-12-24 19:10 UTC
